name = "Evosnn"
uuid = "9ce41316-4a99-4786-a390-a14942961cb3"
authors = ["Emil Dmitruk <e.dmitruk@herts.ac.uk>"]
version = "0.1.1"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ArgParse = "1.2.0"
CSV = "0.10"
Combinatorics = "1.0"
Debugger = "0.7"
DelimitedFiles = "1.9.1"
Distributions = "0.25"
DrWatson = "2.18"
Random = "1.11"
Tables = "1.12"
Test = "1.11"

[extras]
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Debugger"]
